import type { Course } from "./types";

export const mockCourses: Course[] = [
  {
    id: "fullstack",
    slug: "fullstack-development",
    title: "Full Stack Development",
    description: "Build end-to-end web applications from UI to deployment",
    longDescription:
      "Master the complete web development stack. Learn frontend frameworks, backend servers, databases, and cloud deployment. Build 3 production-ready projects and deploy them live.",
    imageUrl: "/courses/fullstack.jpg",
    price: 79000,
    originalPrice: 79000,
    currency: "NGN",
    instructor: {
      name: "Folubandele Oladele",
      title: "Senior Full Stack Engineer",
      imageUrl: "/avatars/folub.jpg",
      bio: "10+ years building web apps at scale. Led teams at fintech startups.",
    },
    rating: 4.8,
    reviewCount: 247,
    studentCount: 1823,
    duration: 180,
    level: "intermediate",
    category: "Development",
    topics: [
      "HTML, CSS, JavaScript, React",
      "Node.js, Express, PostgreSQL",
      "Git, CI/CD, Cloud Deployment",
      "3 Real-World Portfolio Projects",
    ],
    modules: [
      {
        id: "m1",
        title: "HTML & CSS Fundamentals",
        order: 1,
        lessons: [
          { id: "l1", title: "HTML Basics", order: 1, duration: 45 },
          { id: "l2", title: "Semantic HTML", order: 2, duration: 38 },
          { id: "l3", title: "CSS Layouts", order: 3, duration: 52 },
        ],
      },
      {
        id: "m2",
        title: "JavaScript & React",
        order: 2,
        lessons: [
          { id: "l4", title: "JavaScript Fundamentals", order: 1, duration: 90 },
          { id: "l5", title: "React Basics", order: 2, duration: 75 },
          { id: "l6", title: "State Management", order: 3, duration: 68 },
        ],
      },
      {
        id: "m3",
        title: "Backend with Node.js",
        order: 3,
        lessons: [
          { id: "l7", title: "Node.js Setup", order: 1, duration: 30 },
          { id: "l8", title: "Express Server", order: 2, duration: 65 },
          { id: "l9", title: "Database Design", order: 3, duration: 72 },
        ],
      },
    ],
    whatYouLearn: [
      "Build responsive, modern web interfaces with React",
      "Create robust backend APIs with Node.js and Express",
      "Design and manage databases with PostgreSQL",
      "Deploy applications to production (AWS, Vercel, Heroku)",
      "Master Git workflows and CI/CD pipelines",
      "Build 3 complete projects and deploy them live",
    ],
    requirements: [
      "Basic computer literacy",
      "Text editor (VS Code recommended)",
      "Terminal/command line basics",
    ],
    includes: {
      videos: 50,
      projects: 3,
      certificate: true,
      lifetime: true,
    },
    featured: true,
    discount: 40,
  },

  {
    id: "ethical-hacking",
    slug: "ethical-hacking-fundamentals",
    title: "Ethical Hacking Fundamentals",
    description: "Learn penetration testing and cybersecurity from the ground up",
    longDescription:
      "Think like an attacker to defend like a pro. Master the tools, techniques, and mindset of penetration testers. Includes hands-on labs with real hacking scenarios.",
    imageUrl: "/courses/ethical-hacking.jpg",
    price: 75000,
    originalPrice: 75000,
    currency: "NGN",
    instructor: {
      name: "Samuel Adewale",
      title: "Certified Ethical Hacker (CEH)",
      imageUrl: "/avatars/samuel.jpg",
      bio: "Cybersecurity specialist with 8+ years in penetration testing. Consulted for Fortune 500 companies.",
    },
    rating: 4.9,
    reviewCount: 189,
    studentCount: 1205,
    duration: 160,
    level: "intermediate",
    category: "Cybersecurity",
    topics: [
      "Networking & Security Basics",
      "Kali Linux, Nmap, Metasploit",
      "Web App & Network Pentesting",
      "CTF Challenges + Report Writing",
    ],
    modules: [
      {
        id: "m1",
        title: "Networking Fundamentals",
        order: 1,
        lessons: [
          { id: "l1", title: "TCP/IP Basics", order: 1, duration: 50 },
          { id: "l2", title: "DNS & DHCP", order: 2, duration: 42 },
          { id: "l3", title: "Firewalls", order: 3, duration: 48 },
        ],
      },
      {
        id: "m2",
        title: "Reconnaissance & Scanning",
        order: 2,
        lessons: [
          { id: "l4", title: "Information Gathering", order: 1, duration: 60 },
          { id: "l5", title: "Nmap Deep Dive", order: 2, duration: 75 },
          { id: "l6", title: "Vulnerability Scanning", order: 3, duration: 65 },
        ],
      },
    ],
    whatYouLearn: [
      "Master network scanning and reconnaissance techniques",
      "Use professional hacking tools: Nmap, Metasploit, Burp Suite",
      "Conduct web application penetration testing",
      "Write professional security assessment reports",
      "Solve real-world CTF (Capture The Flag) challenges",
      "Understand attacker mindset and defensive strategies",
    ],
    requirements: [
      "Basic networking knowledge",
      "Linux command line basics",
      "Virtual machine setup (VirtualBox or VMware)",
    ],
    includes: {
      videos: 45,
      projects: 5,
      certificate: true,
      lifetime: true,
    },
    featured: true,
    discount: 41,
  },

  {
    id: "machine-learning",
    slug: "machine-learning-foundations",
    title: "Machine Learning Foundations",
    description: "From Python basics to building and training your own ML models",
    longDescription:
      "An practical introduction to artificial intelligence. Learn Python, data science libraries, supervised and unsupervised learning, and build real ML models.",
    imageUrl: "/courses/machine-learning.jpg",
    price: 75000,
    originalPrice: 75000,
    currency: "NGN",
    instructor: {
      name: "Dr. Chioma Okonkwo",
      title: "ML Engineer & Data Scientist",
      imageUrl: "/avatars/chioma.jpg",
      bio: "PhD in Computer Science. Built ML models for recommendation engines and fraud detection.",
    },
    rating: 4.7,
    reviewCount: 156,
    studentCount: 987,
    duration: 140,
    level: "intermediate",
    category: "AI & Data Science",
    topics: [
      "Python, NumPy, Pandas",
      "Supervised & Unsupervised Learning",
      "Neural Networks Introduction",
      "Hands-On ML Projects",
    ],
    modules: [
      {
        id: "m1",
        title: "Python for Data Science",
        order: 1,
        lessons: [
          { id: "l1", title: "Python Basics", order: 1, duration: 55 },
          { id: "l2", title: "NumPy & Pandas", order: 2, duration: 80 },
          { id: "l3", title: "Data Visualization", order: 3, duration: 60 },
        ],
      },
      {
        id: "m2",
        title: "Supervised Learning",
        order: 2,
        lessons: [
          { id: "l4", title: "Linear Regression", order: 1, duration: 70 },
          { id: "l5", title: "Classification Models", order: 2, duration: 75 },
          { id: "l6", title: "Model Evaluation", order: 3, duration: 55 },
        ],
      },
    ],
    whatYouLearn: [
      "Master Python for data science and machine learning",
      "Understand supervised and unsupervised learning algorithms",
      "Build, train, and evaluate machine learning models",
      "Work with real datasets from Kaggle",
      "Implement neural networks and deep learning basics",
      "Deploy ML models to production",
    ],
    requirements: [
      "Python programming basics",
      "High school level mathematics",
      "Computer with 8GB RAM minimum",
    ],
    includes: {
      videos: 40,
      projects: 4,
      certificate: true,
      lifetime: true,
    },
    featured: false,
    discount: 41,
  },

  {
    id: "backend",
    slug: "backend-development",
    title: "Backend Development",
    description: "Build robust APIs and scalable server-side applications",
    longDescription:
      "Design and build the invisible engine behind great products. Master API design, database management, authentication, and cloud deployment.",
    imageUrl: "/courses/backend.jpg",
    price: 69000,
    originalPrice: 69000,
    currency: "NGN",
    instructor: {
      name: "Tunde Akinyemi",
      title: "Backend Architect",
      imageUrl: "/avatars/tunde.jpg",
      bio: "Built microservices for 500K+ daily active users. AWS certified solutions architect.",
    },
    rating: 4.8,
    reviewCount: 198,
    studentCount: 1456,
    duration: 130,
    level: "intermediate",
    category: "Development",
    topics: [
      "Node.js, Express, NestJS",
      "REST APIs & Authentication (JWT)",
      "PostgreSQL & MongoDB",
      "Cloud Deployment (AWS / GCP)",
    ],
    modules: [
      {
        id: "m1",
        title: "RESTful API Design",
        order: 1,
        lessons: [
          { id: "l1", title: "API Principles", order: 1, duration: 50 },
          { id: "l2", title: "Building APIs", order: 2, duration: 70 },
          { id: "l3", title: "Error Handling", order: 3, duration: 45 },
        ],
      },
      {
        id: "m2",
        title: "Database Management",
        order: 2,
        lessons: [
          { id: "l4", title: "SQL Basics", order: 1, duration: 65 },
          { id: "l5", title: "NoSQL Databases", order: 2, duration: 60 },
          { id: "l6", title: "Database Performance", order: 3, duration: 55 },
        ],
      },
    ],
    whatYouLearn: [
      "Design professional REST and GraphQL APIs",
      "Implement authentication and authorization",
      "Build and optimize database queries",
      "Handle real-time data with WebSockets",
      "Deploy to AWS, GCP, or DigitalOcean",
      "Scale applications for millions of users",
    ],
    requirements: [
      "JavaScript fundamentals",
      "Basic SQL knowledge helpful",
    ],
    includes: {
      videos: 45,
      projects: 3,
      certificate: true,
      lifetime: true,
    },
    featured: false,
    discount: 43,
  },

  {
    id: "frontend",
    slug: "frontend-development",
    title: "Frontend Development",
    description: "Craft beautiful, fast, and accessible user interfaces",
    longDescription:
      "Master modern web development. Build fast, responsive, and accessible UIs with React and Next.js. Learn design principles and user experience best practices.",
    imageUrl: "/courses/frontend.jpg",
    price: 65000,
    originalPrice: 65000,
    currency: "NGN",
    instructor: {
      name: "Ife Okafor",
      title: "Senior Frontend Engineer",
      imageUrl: "/avatars/ife.jpg",
      bio: "Design system lead at tech startup. Accessibility specialist. Open source contributor.",
    },
    rating: 4.7,
    reviewCount: 234,
    studentCount: 2103,
    duration: 110,
    level: "beginner",
    category: "Development",
    topics: [
      "HTML5, CSS3, JavaScript",
      "React.js & Next.js",
      "Responsive & Accessible UI",
      "Component-Based Architecture",
    ],
    modules: [
      {
        id: "m1",
        title: "HTML & CSS Mastery",
        order: 1,
        lessons: [
          { id: "l1", title: "Modern HTML", order: 1, duration: 50 },
          { id: "l2", title: "Advanced CSS", order: 2, duration: 65 },
          { id: "l3", title: "Responsive Design", order: 3, duration: 60 },
        ],
      },
      {
        id: "m2",
        title: "React Fundamentals",
        order: 2,
        lessons: [
          { id: "l4", title: "React Basics", order: 1, duration: 70 },
          { id: "l5", title: "Hooks & State", order: 2, duration: 75 },
          { id: "l6", title: "Component Patterns", order: 3, duration: 65 },
        ],
      },
    ],
    whatYouLearn: [
      "Build responsive websites that work on all devices",
      "Create interactive UIs with React and Next.js",
      "Master CSS animations and transitions",
      "Implement accessible web interfaces (WCAG)",
      "Optimize performance and Core Web Vitals",
      "Deploy to Vercel and other hosting platforms",
    ],
    requirements: [
      "Basic programming knowledge",
      "Text editor (VS Code)",
    ],
    includes: {
      videos: 35,
      projects: 4,
      certificate: true,
      lifetime: true,
    },
    featured: false,
    discount: 43,
  },

  {
    id: "prompt-engineering",
    slug: "prompt-engineering",
    title: "Prompt Engineering",
    description: "Master AI tools and build AI-powered products",
    longDescription:
      "Learn to design, chain, and deploy prompts that turn large language models into powerful business tools and products.",
    imageUrl: "/courses/prompt-engineering.jpg",
    price: 40000,
    originalPrice: 40000,
    currency: "NGN",
    instructor: {
      name: "Chidi Obi",
      title: "AI Product Specialist",
      imageUrl: "/avatars/chidi.jpg",
      bio: "Built AI features for 100K+ users. Prompt engineering practitioner since GPT-3. Open AI ambassador.",
    },
    rating: 4.6,
    reviewCount: 142,
    studentCount: 845,
    duration: 90,
    level: "beginner",
    category: "AI Tools",
    topics: [
      "LLM Fundamentals & APIs",
      "Prompt Design & Chaining",
      "RAG, Agents & Tool Use",
      "Build AI-Powered Products",
    ],
    modules: [
      {
        id: "m1",
        title: "LLM Fundamentals",
        order: 1,
        lessons: [
          { id: "l1", title: "How LLMs Work", order: 1, duration: 45 },
          { id: "l2", title: "API Basics", order: 2, duration: 50 },
          { id: "l3", title: "Model Comparison", order: 3, duration: 40 },
        ],
      },
      {
        id: "m2",
        title: "Prompt Engineering",
        order: 2,
        lessons: [
          { id: "l4", title: "Prompt Principles", order: 1, duration: 55 },
          { id: "l5", title: "Chain of Thought", order: 2, duration: 50 },
          { id: "l6", title: "Advanced Techniques", order: 3, duration: 60 },
        ],
      },
    ],
    whatYouLearn: [
      "Understand how large language models work",
      "Write effective prompts for any task",
      "Chain prompts for complex workflows",
      "Build RAG (Retrieval Augmented Generation) systems",
      "Create AI agents that take actions",
      "Deploy LLM applications to production",
    ],
    requirements: [
      "No prior AI knowledge required",
      "Familiarity with APIs helpful",
      "ChatGPT or Claude account",
    ],
    includes: {
      videos: 30,
      projects: 3,
      certificate: true,
      lifetime: true,
    },
    featured: false,
    discount: 42,
  },
];
